### PR TITLE
Add extra axolotl variants textures & Splash change

### PR DESCRIPTION
**Pull request by NormalFery**
Pretty much what it says
Imma be honest i'd try to implement the variants _code wise_ but getting MAVAPI to work seems like a pain in the ass

### CODE REVIEW

**Review by blryface — APPROVED** [review]
the files seem quite big but I think we can ask ampflower to optimize later

**Comment by NormalFery** [comment]
ETA : idk man can we even copy them? 
File size : i blame windows or smth

**Comment by blryface** [comment]
> ETA : idk man can we even copy them? 

It's licensed MIT

> File size : i blame windows or smth

Probably p2s

**Comment by NormalFery** [comment]
> It's licensed MIT

It says Apache 2.0 on [The API repo](https://github.com/AkashiiKun/MoreAxolotlVariantsAPI-Common?tab=License-1-ov-file) though

**Comment by blryface** [comment]
Oh they didn't update the modrinth catstar

**Pull request merged**
